### ISSUE TITLE
please release new version 

### ISSUE THREAD

**Issue by rbda** [aptivate/django-sortable-listview#15]
please release new version to reflect changes to master branch. Pip installs .41 as latest version.

Thanks

**Comment by martinburchell** [comment]
Thanks for the reminder. Will aim to do this week

**Comment by rbda** [comment]
Thanks very much!

**Comment by martinburchell** [comment]
0.42 should now be available

**Comment by birdsarah** [comment]
@martinburchell can you do another release now the py3 code is merged?

**Comment by birdsarah** [comment]
@martinburchell if you want to add me as a co-maintainer on pypi i can also push releases. i'm `birdsarah`.

**Comment by martinburchell** [comment]
@birdsarah yes can do that a bit later if you're keen. If you were up for updating the changelog that would be awesome.
