### ISSUE TITLE
Sorting over computed fiels

### ISSUE THREAD

**Issue by kornicameister** [aptivate/django-sortable-listview#8]
I would like be able to run sorting over model methods, annotated with 

``` python
@property
```

Unfortunately, currently it seems that it is not supported.

**Comment by birdsarah** [comment]
That sounds very useful. Not sure when I'll get a chance to work on it, but, obviously, happy to review a PR.

**Comment by kornicameister** [comment]
I did a little experiment and as it turns out the fault it does not work lies somewhere else. It is simply not supported in DjangoORM. Here You can see how I did that, [link](https://github.com/kornicameister/DTodo/blob/master/DTodo/view/todo/todo.py#L54). 

As for the issue addressed here. I believe that there are two options. Since this is rather straightforward it would be possible to hide this feature within the vie but on the other hand...it is very simple and takes just couple of lines.=

Anyway I will try to submit some PR as soon as possible.

Best regards,
kornicameister
